name: Debug
on: issues
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Artifacts
        uses: mheap/debug-artifact@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
