on:
  push:
    branches:
      - master
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/setup-deck@v2
        with:
          deck-version: 1.7.0
          wrapper: true
      - run: deck version
        id: deck_version
      - run: echo '${{ toJson(steps.deck_version.outputs) }}'
