name: Docker Build and Push
on:
  push:
  release:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Push
        uses: mheap/action-test@master
        with:
          image_name: mheap/action-test
