name: Dynamic Matrix
on: push
jobs:
  create_matrix:
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        run: echo "::set-output name=version_matrix::$(curl https://laravelversions.com/api/versions | jq -c '[.data[] | select(.status=="active") | .latest]')"
    outputs:
      version_matrix: ${{ steps.set-matrix.outputs.version_matrix }}

  ci:
    needs: create_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.create_matrix.outputs.version_matrix) }}
    steps:
      - run: echo "Running tests for Laravel ${{ matrix.version }}"
