name: Manual Approval
on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
    pull_number:
      description: "Pull Request to approve"
      required: true
jobs:
  mark-pending:
    name: Mark PR as pending
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          debug: true
          script: |
            const data = await github.repos.createStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: "pending",
              context: "manual-approval",
              description: "This PR needs manual approval"
            });

            console.log(data);

  approve:
    name: Approve PR
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Hello world
        run: echo "Job Approved"
