name: Paths Test
on:
  push:
    paths:
      - "mkdwn/**.md"
jobs:
  frontmatter-json-schema-validator:
    name: Frontmatter JSON Schema Validator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Frontmatter JSON Schema Validator
        uses: mheap/frontmatter-json-schema-action@main
        with:
          paths: "mkdwn/*.md"
          schema: '{"type":"object","properties":{"title":{"type":"string"},"description":{"type":"string"}},"required":["title"],"additionalProperties":false}'
