name: Push Test
on: push
jobs:
  node-version:
    name: node14
    runs-on: ubuntu-latest
    steps:
      - name: Markdown Meta
        uses: mheap/markdown-meta-action@main
        id: meta
        with:
          file: ./foo.md
      - name: Use the value
        run: echo "${{ steps.meta.output.title }}"
