name: Inso
on:
  workflow_dispatch:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
    name: Install Inso
    runs-on: ${{matrix.runner}}
    steps:
      - uses: mheap/setup-inso@v1
        with:
          inso-version: 2.4.0
      - run: inso --version
